### ISSUE TITLE
The url in v3 should end with a / else a 404 not found is returned

### ISSUE THREAD

**Issue by sommmen** [serilog-contrib/serilog-ui#128]
Just migrated to v3 and after considerable headache it seems like for some reason https://localhost:5001/serilog-ui/ seems to work but https://localhost:5001/serilog-ui gives a 404.
I'm seeing this on both chrome and firefox and this happens under the default configuration.

**Comment by followynne** [comment]
Hey @sommmen 👍 

that's a requirement I had due to client-side routing that is listed [here](https://github.com/serilog-contrib/serilog-ui/wiki/Configure#b-register-middleware-in-the-net-request-pipeline), in the WithRoutePrefix XML comments

I'll keep the issue open to see if I can make it work also without the end slash - I'm not sure I can do it, due to [how routing works](https://github.com/serilog-contrib/serilog-ui/blob/1dd8f135ad0b3dc5a57e95ddb9e30400f6303093/src/Serilog.Ui.Web/SerilogUiMiddleware.cs#L55) on the middleware

**Comment by sommmen** [comment]
Hm, I think I see what you're getting at. How about a simple redirect to add the slash? Not super pretty but will save a lot of headache. I've also seen this done before.

**Comment by followynne** [comment]
Released in v3.0.1.
