### ISSUE TITLE
Add back EnableAuthorization or provide equivalent example

### ISSUE THREAD

**Issue by FixFlare** [serilog-contrib/serilog-ui#71]
First of all, great project, thanks for your work on this.

I've been using this in a work project for a few months now and updated to the latest version today only to find out my project wouldn't build any longer because of the removal of "EnableAuthorization"

Can I ask why this was removed and if there is any place I can look out for breaking changes like this to be communicated in the future?

I had to look at the commit history to make sure I wasn't crazy since there didn't seem to be a mention of its removal in the readme:

[https://github.com/mo-esmp/serilog-ui/commit/0ec56848973daa5b130702a0d6613a9255cdc858#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L89](https://github.com/mo-esmp/serilog-ui/commit/0ec56848973daa5b130702a0d6613a9255cdc858#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L89)

I thought it was a very useful feature. If there aren't any plans to add it back, do you think we could get an equivalent example on the readme instead of the trimmed down "isAuthenticated" one?

Thanks

**Comment by mo-esmp** [comment]
@FixFlare Sorry for the inconvenience, authorization mechanism has changed, please check out [authorization](https://github.com/mo-esmp/serilog-ui#authorization) section. By default serilog-ui allows access to the log page only for local requests. In order to give appropriate rights for production use, you need to configure authorization. You can add your own implementations of the IUiAuthorizationFilter interface, whose Authorize method is used to allow or prohibit a request. The first step is to provide your own implementation:
```csharp
appBuilder.UseSerilogUi(options =>
{
    options.Authorization.AuthenticationType = AuthenticationType.Jwt;
    options.Authorization.Filters = new[]
    {
        new CustomAuthorizeFilter()
    };
});
```
If you set AuthenticationType to Jwt, you can set a JWT token and an Authorization header will be added to the request and for Cookie just login into your website and no extra step is required.

Here is an example of how you can implement your own authentication and authorization:
```csharp
public class CustomAuthorizeFilter : IUiAuthorizationFilter
{
    public bool Authorize(HttpContext httpContext)
    {
        return httpContext.User.Identity is { IsAuthenticated: true };
    }
}
```

**Comment by mo-esmp** [comment]
@FixFlare Let me know if you need any help here to implement your authorization scenario.

**Comment by mo-esmp** [comment]
Feel free to reopen it whenever necessary.
